#!/bin/sh

$HOME/.config/bspwm/polybar/launch.sh &
sxhkd &
nm-applet &
variety &
#dropbox &
pamac-tray &
compton --config $HOME/.config/bspwm/compton.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
#nitrogen --restore &
#caffeine &

bspc config border_width          5
bspc config window_gap            15
bspc config top_padding           20
bspc config single_monocle        true
bspc config focused_border_color  \#525256
bspc config click_to_focus	 true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp state=floating follow=on
bspc rule -a Xfce4-appfinder  state=floating sticky=on
bspc rule -a Gpick state=floating sticky=on
bspc rule -a mpv state=floating sticky=on
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a feh state=floating
bspc rule -a Nitrogen state=floating 
bspc rule -a Lxappearance state=floating 

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window


